name: Launcher Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ubntu_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: npm install
        run: npm install
      - name: install TypeScript
        run: npm install -g typescript
      - name: Build Launcher
        run: npm run publish-linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Namagomi-Launcher
          path: assets/installer/Namagomi-Launcher.AppImage

  mac_build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: npm install
        run: npm install
      - name: install TypeScript
        run: npm install -g typescript
      - name: Build Launcher
        run: npm run publish-mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Namagomi-Launcher
          path: assets/installer/Namagomi-Launcher.dmg

  win_build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: npm install
        run: npm install
      - name: install TypeScript
        run: npm install -g typescript
      - name: Build Launcher
        run: npm run publish-win-x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Namagomi-Launcher
          path: assets/installer/Namagomi-Launcher.exe