name: Launcher Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ubntu_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Create dot env file
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: echo $DOT_ENV | base64 --decode > .env
      - name: npm install
        run: npm install
      - name: install TypeScript
        run: npm install --location=global typescript
      - name: Build Launcher
        run: npm run publish-linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Namagomi-Launcher
          path: assets/installer/Namagomi-Launcher.AppImage

  mac_build:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      P12PASS: ${{ secrets.P12PASS }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Create dot env file
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: echo $DOT_ENV | base64 --decode > .env
      - run: security create-keychain -p password my.keychain
      - run: security default-keychain -s my.keychain
      - run: security unlock-keychain -p password my.keychain
      - run: security set-keychain-settings my.keychain
      - run: security import namagomi-launcher.p12 -k my.keychain -A -P $P12PASS
      - run: "security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k password my.keychain"
      - run: security list-keychains -s my.keychain
      - run: security find-identity -v
      - name: npm install
        run: npm install
      - name: install TypeScript
        run: npm install --location=global typescript
      - name: Build Launcher
        run: npm run publish-mac
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Namagomi-Launcher
          path: assets/installer/Namagomi-Launcher.dmg

  win_build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Create dot env file
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: echo $DOT_ENV | base64 --decode > .env
      - name: npm install
        run: npm install
      - name: install TypeScript
        run: npm install --location=global typescript
      - name: Build Launcher
        run: npm run publish-win-x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ~/namagomi_launcher.p12
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Namagomi-Launcher
          path: assets/installer/Namagomi-Launcher.exe