name: Launcher Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ubntu_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: npm install
        run: npm install
      - name: install TypeScript
        run: npm install -g typescript
      - name: Build Launcher
        run: npm run publish-linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Namagomi-Launcher
          path: assets/installer/Namagomi-Launcher.AppImage
      - name: Create dot env file
        shell: bash
        run: |
          touch .env
          echo "CLIENT_ID=9afa5262-e6db-4497-a79b-08f17e684f24" >> .env
          echo "TENANT_ID=consumers" >> .env
          echo "REDIRECT_URI=msal://redirect" >> .env
          echo "AD_ENDPOINT_HOST=https://login.microsoftonline.com/" >> .env
          echo "GRAPH_ENDPOINT_HOST=https://graph.microsoft.com/" >> .env
          echo "GRAPH_ME_ENDPOINT=v1.0/me" >> .env
          echo "GRAPH_MAIL_ENDPOINT=v1.0/me/messages" >> .env
          echo "APPLEID=yuuki1293@outlook.jp" >> .env
          echo "APPLEIDPASS=${{ secret.APPLEIDPASS }}" >> .env
          echo "ASC_PROVIDER=${{ secret.ASC_PROVIDER }}" >> .env

  mac_build:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: security create-keychain -p password my.keychain
      - run: security default-keychain -s my.keychain
      - run: security unlock-keychain -p password my.keychain
      - run: security set-keychain-settings my.keychain
      - run: security import namagomi-launcher.p12 -k my.keychain -A -P ${{ secret.P12PASS }}
      - run: "security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k password my.keychain"
      - run: security list-keychains -s my.keychain
      - run: security find-identity -v
      - name: npm install
        run: npm install
      - name: install dmg-license
        run: npm i dmg-license
      - name: install TypeScript
        run: npm install -g typescript
      - name: Build Launcher
        run: npm run publish-mac
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Namagomi-Launcher
          path: assets/installer/Namagomi-Launcher.dmg

  win_build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: npm install
        run: npm install
      - name: install TypeScript
        run: npm install -g typescript
      - name: Build Launcher
        run: npm run publish-win-x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Namagomi-Launcher
          path: assets/installer/Namagomi-Launcher.exe