name: Launcher Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ubntu_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Create dot env file
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: echo $DOT_ENV | base64 --decode > .env
      - name: npm install
        run: npm install
      - name: install TypeScript
        run: npm install --location=global typescript
      - name: Build Launcher
        run: npm run publish-linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Namagomi-Launcher
          path: assets/installer/Namagomi-Launcher.AppImage

  mac_build:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      P12PASS: ${{ secrets.P12PASS }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Create dot env file
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: echo $DOT_ENV | base64 --decode > .env
      - run: security create-keychain -p password my.keychain
      - run: security default-keychain -s my.keychain
      - run: security unlock-keychain -p password my.keychain
      - run: security set-keychain-settings my.keychain
      - run: security import namagomi-launcher.p12 -k my.keychain -A -P $P12PASS
      - run: "security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k password my.keychain"
      - run: security list-keychains -s my.keychain
      - run: security find-identity -v
      - name: npm install
        run: npm install
      - name: install TypeScript
        run: npm install --location=global typescript
      - name: Build Launcher
        run: npm run publish-mac
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Namagomi-Launcher
          path: assets/installer/Namagomi-Launcher.dmg

  win_build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Create dot env file
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: echo $DOT_ENV | base64 --decode > .env
      - name: npm install
        run: npm install
      - name: install TypeScript
        run: npm install --location=global typescript
      - name: Build Launcher
        run: npm run publish-win-x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: MIIM0gIBAzCCDJkGCSqGSIb3DQEHAaCCDIoEggyGMIIMgjCCBs8GCSqGSIb3DQEHBqCCBsAwgga8AgEAMIIGtQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIMafw51CzW8ACAggAgIIGiFxum9ETgDaB3fc0gAF0gXuj5NAtZwhh1L6DrayZxPrpO5ylpkeR/upbeVu0CuXJEBbk3j89WKi4jS4uw3Sa26/VPUyRqHsnVqvFVWRyVOlaDnsNKfJx6Ls7T8111OrIN9NjYwvbuS2nvFattx2eoX1GgTv0AsP7tvIIyL4CE0a/ABtVrpVyZekegCj18mbL/RLYBncEQAIdJvAG7pmtl4lXE8sQzEdqrYIXJX1DMbaxLnHwgdPlAEO5Ls1LRCskjjtV1x5pF+BeDIU/XWKlwjtWxPgKKUm40cU2cJj6AKxs2UIRDUpF/OahrDtF6mXAvPKRJorW6f160P026sHjvx38dylqJPh5ruP4K9BZb+vdfarRhIpMrD2/R0Xu7J6KEKbEYzDqnT/CkO5KV7F4S++vpBXbnMBkNdMLJ8Dpwrtun05To/rGw7KOOxMDiDZcOvolUjqV7bt+SJnthRZllUNJu2Ice+8cRqThMgR23BCteF4xgi3O2nflsuhbTJZvZJv1eqd9+8K0w5mS6ROrMhklrzZaz2pKLPsshcJVhLjwmS7keVnL9kU6D3ZWOdEQ6J/y69oxUE9ODRusS3FhlXXP0WasENm9qnf+KlxvHCJKfuEjblQT56+YOLuRMUpVZUi21NsI/L9dkqUP3tFWQH7dSqSmOX36k+QIy7Y9hSC28SSALAE/lOrGcuoA+P5MisuX41f7rVHxFxagxF4WxcOwT6mB18LjsFHNKSlKneHOGDASHhGgWFA9LJpsezBxZf0Oc3GLfDWYqoskwXwDNYlakSa7PqFD94BV7HQzwu19mRdRsZgMItb2qicDHZNvyIibDNcd0ha6+GfOlmSoIi1/zNUCs2iAowF6lWJaSmZwqH4M8PSvAHD/xv6cgJS2zZCL1HoJSJ/8LEhIdBu1Yo4OGaJY6UBdCgpMtDU8PL21uopIs3VbdQq+1I02QCPzQ1fP40Lg56EXA3mGSy/BTCJFLiiyrYp7xFRbaCLTpiaP8IsehQz0lALkmhBXPu/5Uk5ZKniJm88qq/SRW3uvziVGmVnEcwoBw177aPxbbRzqcBFRcgJo+u5q01qsxER3XZzjQs78sBVjPVW1XnbZMEnwzvlqiSgTIJKFx15iT9RsPaFARk9vU2oPPlBNdv+Lv9woOUV2X2VuSS1emyXQuCbgIcByQ1pjA5d6CXRpRY6T++CqcNNRbeDMvxmQsbadNDCdvgDdC4RwrJlnuC8PJMGKKR3dHDSt+mJcYPZCLRnXBU7eGApah52wmGBum71pTJ2Rt0o23SZknoc0ObLJTiAd0iZnwoM9eU/kVGuCcX6W19BA7vYXdRopJZyJ6zHOMVocX712osc1t5fcM1fUs1GuyrIzRaTldBhteByS8ukUOTKgSBh2X5dT4cRW7xXyivqZBWl834yMS+awiHBRaikIaBgtN4Oxk6YUoTSD1N1U1FFdYiHe6NHt3+YNOYACNOSBV4kXmJZf9PD0UCQK9m5HwN3p5u5EUt4nyIRYpim+bXdf5nDTwnAYSxLt9WmSClaUhXo7zL6VSI1yWp3sWhk4tvCDr8fi27AImfgSj4AcivTNbw7+6Zq14qQfwegCYnfd7Y2vCfCd7ebHgB4lXQ+PNYemZuyBbbKyzVwdxQY1TLjXeIRRG4BPg08B7iMG3WRxYN7ZrxZ7AXRR6OKhUgO4wVli8HtD63/g9nNZt0e4RWrNn3oa++kE8JwSm7IAyvsz+9T9sLYG1F1xztpQ/Mr8UPNDTQ/ZW3XqO9w8an1Axul8W7EtSfqFCr+nC3N4bQ6lO7ggQnVcJ2l7zaM5fqRxBINU83jS4/HcM6LnjCKFtIQKuWbJenb7KBxkNd4S2Ir34AYrsJqJl6qmrl6JzAGYJQoXloUNxoDIqnCnJ6J8NtuxL+m41IV5EfYTkuof+5DHn0p1sMDRuo7tAzXX8GEl01f+8vVzHTOD+oPVL6ZjMRx1w901Rt4zgbzW/gdE/qm8WjcxqNKoyGKWnvXsi+OirintzKcun9mQ/oVbD4mnCJgzNgDjaaaLQ2iL6Q7qVCOruPmdjNh3TaY4CMiuZddJjiYW+mz+FirDpQDyKjIDJcWNBeao8ZSYuEna+wRNPxoU0G6MbKIJM3TVH25LcuB69doh3Skef2Vy03zDeB692ZK+QhcNEpKEWKP+l9ZqNQL4gI/IjXxuhV5Aj+IWOpWaxO+IDM6NpC8WSjGKYw6PaOCrU4F2oKMwggWrBgkqhkiG9w0BBwGgggWcBIIFmDCCBZQwggWQBgsqhkiG9w0BDAoBAqCCBO4wggTqMBwGCiqGSIb3DQEMAQMwDgQIhoxRMAS2G3oCAggABIIEyPpXSnyD8sDieMKWYL8LMhe/kWgQY8L5i/AaH+h5cmGVVl9FJVhQ2jKKJHFpZfg/OGq3gJyx/NzZkP+Q0cypazBLw3DJkIlbQ8T5BoA6DPO4I3EV1qEjEnYlRmD3wvEcmh7m1J7VOnFLnt54fh6pLSN8ERRD3WclqumbpiVJo7Iy/+iPtUroGt9sH30wp7y2KELXyhtwSCqZrP82aWbpzrkgt9bIShrKh3RmI1vDctZ8Fk4eP13WvOBVXJP4J64ZfyqbJVihFSMjDbtgcsRbDoXy8/5l34aNqQcrR9Zoeak/63MkspOwuBg4WM/3u4nXpwdo9fKanMJHXDX+uF/hLxpYVm5w+avpv+AKKphGdygVfe/U1mjEeu+3lDmJ6NuEqWGMqTf8bLs9dgsDur4QBWPIYMf2Ih+9ONSrZ8Xumfp8N705new2/l69wrU9UCfNUqJmBm2TirRHEsL2dM363oHyHcL1rjnSJhlBaR6jgmtNIPqBxXxJEDoDHvlkKOUgItBDdJfCnOyFyCAyU0AukB53OqwavyGReQou+18GfRi/CEHa28t4M8SsXYF5RZsgmdQkszFYYey6aVp27a3imHzjY0TGVXPyx1vTIx0rFe20LSR3VukgOUC5QpmzNw9gbm+GRPSkZbHtHoW8iPJeXUuAp2QACEPn2bLo4sw6dSpzsmPSGLgFJxdqCsEY1LbhFQmwgGKzOjNLAe3tYfJhAO5fMXrpLb2PDAD4r4IRxW7DN97qshux7ApXhZeO2CYsSN3Wfn5eqaPgdanasoLkhmYxpFueAef6AWblUsTwNsoyiiEZU51cGtbXiPy/7IWokGkiH9K5+xKrBWh+i811JhyQAMgw0XCydVGsALSGkEVpdzN14Qiy8Pf55lQHSm+4ciThJZ3/s3Xj0YRBaQGmgQsv1vkKEnUq1DEdnc+5c9QkAw9SSgxC9w/a+U6NtbiIzF7O074bsX76mLjhuboigGD1XIrFfkg1A6kDJeFFMMfi+6pAwlYLYt9U55wCynnGl2d5+FCXYqzSPqjxsJPH3n0QlKdxMsuUr4GAN+d1tHWnCzzhRv6YFO153mludrn7NZJ/CaihIx0s56F63FA1pVeJ9uRIKb4rL/7asyM74ZtjgQMQyrqdnBi4XKHWN8uZAbqWdE9PlejKqUiXia8KPZuD7AfoW9g+GvI7+LEzobW5OiXNHuFKrR41ePfCr1/+tKROo52WuyQ331N1hiT8o+ot1XFikGrBlXQkDjlLoL6n3SXXSy51BTNBejQ59ADIVMddKQmzPQ+b1EJKqsGuq6mKnRVZwUajYUR1SBgaa9sma0G2jq8yglSnWLscVD5f8PtMXKruIPhD9qzBWA8F7aFBUt6LCmW0vOwi7vMOnNVoDena1pi8j12ry2oOoxf4PLxhATr7wzjGx6EeS5AWfM1jAciQKQhtKUT8oKvJ8RSN/jPMMUBKpdpC4QYaFcPGxdtJQ/jvaRGhWCQjELIwpL/41k5ML+CRb0TYUDZU5VUmnyIx1W4gxSS2VvoVc+Ga7u/eT1KneG3bm9S114rff2OXIqzaBoe5YndWmPYodRZqc+VSkBSV79cmkAi/IXtWwdSsOsYIB149YwRJ+DjFDY7GmUxWO5TFWjGBjjBnBgkqhkiG9w0BCRQxWh5YAE0AYQBjACAARABlAHYAZQBsAG8AcABlAHIAIABJAEQAIABBAHAAcABsAGkAYwBhAHQAaQBvAG4AOgAgAHkAdQB1AGsAaQAgAG4AYQBrAGEAbQB1AHIAYTAjBgkqhkiG9w0BCRUxFgQUDv4NIlBcCJFFsjkTfmpWnM3yxAcwMDAhMAkGBSsOAwIaBQAEFD/vQj735psX3LySGbQW68Bsf4hCBAgUO+WrvedJPAIBAQ==
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Namagomi-Launcher
          path: assets/installer/Namagomi-Launcher.exe