name: Launcher Release

on:
  push:
      tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # ${{ github.ref }}ではいらないものもついてくるらしくtag名だけを取得する
      # 参考: https://zenn.dev/mh4gf/scraps/7cd842bc59b8e0
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: NamagomiLauncher - ${{ env.RELEASE_VERSION }}
          body: |
            ✅ ごみデザイン
            ✅ 未署名
            ✅ 未デバッグ
            ✅ 大量のバグ
          draft: false
          prerelease: false

  ubntu_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: npm install
        run: npm install

      - name: install TypeScript
        run: npm install -g typescript

      - name: Build Launcher
        run: npm run publish-linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'assets/installer/Namagomi-Launcher.AppImage'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  mac_build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: npm install
        run: npm install

      - name: install TypeScript
        run: npm install -g typescript

      - name: Build Launcher
        run: npm run publish-mac-x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'assets/installer/Namagomi-Launcher.dmg'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ env.RELEASE_VERSION }}

  win_build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs  
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: npm install
        run: npm install

      - name: install TypeScript
        run: npm install -g typescript

      - name: Build Launcher
        run: npm run publish-win-x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'assets/installer/Namagomi-Launcher.exe'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ env.RELEASE_VERSION }}